apiVersion: v1
kind: Namespace
metadata:
  name: mjb-aks-cosmosdb
---
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: mjb-aks
  namespace: mjb-aks-cosmosdb
spec:
  location: eastus
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: DatabaseAccount
metadata:
  name: mjb-aks-cdb
  namespace: mjb-aks-cosmosdb
spec:
  location: eastus
  owner:
    name: mjb-aks
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: eastus
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabase
metadata:
  name: database1
  namespace: mjb-aks-cosmosdb
spec:
  location: eastus
  owner:
    name: mjb-aks-cdb
  resource:
    id: database1
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabaseContainer
metadata:
  name: container1
  namespace: mjb-aks-cosmosdb
spec:
  location: eastus
  owner:
    name: database1
  resource:
    id: container1
    partitionKey:
      kind: Hash
      paths: ["/pk"]
  options:
    autoscaleSettings:
      maxThroughput: 4000