apiVersion: v1
kind: Namespace
metadata:
  name: mjb-aks-cosmosdb
---
apiVersion: microsoft.resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: mjb-aks
  namespace: mjb-aks-cosmosdb
spec:
  location: westcentralus
---
apiVersion: microsoft.documentdb.azure.com/v1alpha1api20210515
kind: DatabaseAccount
metadata:
  name: mjb-aks-cdb
  namespace: mjb-aks-cosmosdb
spec:
  location: eastus
  owner:
    name: mjb-aks-cdb
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: eastus
